apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lab
  region: us-west-2

nodeGroups:
  - name: lab-ng-a
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true
    availabilityZones: ["us-west-2a"]
  - name: lab-ng-b
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true
    availabilityZones: ["us-west-2b"]


vpc:
  id: "vpc-0470143a7c277ae00"  # (optional, must match VPC ID used for each subnet below)
  cidr: "192.168.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    private:
      us-west-2a:
        id: "subnet-09020bc85e58f9bbf"
      us-west-2b:
        id: "subnet-0620283eb6fe258cc"
      us-west-2d:
        id: "subnet-0f95d03db1bdf9109"
    public:
      us-west-2a:
        id: "subnet-0f5359d858ba4098d"
      us-west-2b:
        id: "subnet-0548de7d8ab9a2c5e"
      us-west-2d:
        id: "subnet-0fc8964f4bc35681f"

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]